### PR TITLE
Add sorting by server group

### PR DESCRIPTION
**Pull request by StrixG**
- Added two new sorting elements: `SERVER_GROUP` and `SERVER_GROUP_NAME`

`SERVER_GROUP` sorts by the order of groups in `server_groups`.

For example with the following configuration:
```yaml
server_groups:
  lobbies:
  - lobby1
  - lobby2
  survival:
  - survival
  creative:
  - creative
  minigames:
  - bedwars
  - skyblock
```

Order of the groups would be: `lobbies, survival, creative, minigames, <other servers>...`

### CODE REVIEW

**Comment by WiIIiam278** [comment]
Really nice work! A few little points
- Id like to move away from the sorting key system in favour of the key being generated based on a placeholder-replaced string
- Instead of “server group order”, how about just using the existing map keys? Annotaml supports the use of a LinkedHashMap to preserve order so should work fine if you change the group maps over to use this; rather than adding another config option

**Comment by StrixG** [comment]
Great idea! That would be a much cleaner solution. Didn't know that it supports LinkedHashMap.

**Comment by StrixG** [comment]
Ready for review

**Review by WiIIiam278 — APPROVED** [review]
Approving -- but could you quickly update the docs https://github.com/WiIIiam278/Velocitab/blob/master/docs/Sorting.md#list-of-elements too for me?

**Comment by StrixG** [comment]
Updated. But I'm not sure about the description. English is not my first language.

**Comment by WiIIiam278** [comment]
Perfect -- no worries. Thank you!

**Pull request merged**
