### PR TITLE
Fix player kick handler

### PR DESCRIPTION
**Pull request by courat-private**
- When a player was kicked from a Minecraft Server he was removed from the tablist.

### CODE REVIEW

**Review by WiIIiam278 — APPROVED** [review]

**Comment by WiIIiam278** [comment]
Seems good to me, but want to check with @alexdev03 too :)

**Comment by alexdev03** [comment]
I think this creates inconsistency in the way that if a player is kicked and redirected to another server with different server group, you may be able to still see the player on the tablist.

**Comment by courat-private** [comment]
you're right, I did not think about that because i'm not using groups :(

**Comment by alexdev03** [comment]
the redirect check should be called before the join on the new server. So first we clear player's tab list and remove him from all tabslists. And then if he joins a server in the same group we handle that as a normal join.

**Pull request closed without merging**
