### PR TITLE
Fix sorting by server

### PR DESCRIPTION
**Pull request by DaJokni**
Sorting by server was documented in the config, but it wasnt enabled or smthn, this fixes that & has been tested to be functional

### CODE REVIEW

**Comment by WiIIiam278** [comment]
Thanks for your interest in contributing! Appreciate it :)

However, I do keep this off by default for a reason: There's a limit of 16 characters that may be used for sorting users (max name of a scoreboard team), so this is unlikely to be effective as the String#compare-safe weight + name of the users' role is likely to fill that capacity already :) 

Secondly, more specific team names means more scoreboard team packets, which is less efficient.

If you think the docs aren't clear, feel free to PR those separately or tell me where you think it's unclear.

**Comment by DaJokni** [comment]
the feature that was said to be there under the name SERVER resulted in an error, stating that it didnt exist

**Comment by WiIIiam278** [comment]
Oh, it should be "SERVER_NAME" in the docs.

**Comment by DaJokni** [comment]
right, ill close this

**Pull request closed without merging**
